CREATE TABLE loan
(
    ID          BIGSERIAL PRIMARY KEY,
    SIGNED_DATE TIMESTAMP,
    END_DATE    TIMESTAMP,
    AMOUNT      DECIMAL(20, 2)
);

CREATE TABLE borrower
(
    ID         BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME  VARCHAR(100)
);

CREATE TABLE loans_to_borrowers
(
    ID          BIGSERIAL PRIMARY KEY,
    LOAN_ID     BIGINT,
    BORROWER_ID BIGINT,
    FOREIGN KEY (BORROWER_ID) REFERENCES borrower (ID),
    FOREIGN KEY (LOAN_ID) REFERENCES loan (ID)
);